# Generated by Django 5.2.7 on 2026-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_offer_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
