# Generated by Django 5.2 on 2026-01-09 10:32

import api.models
import api.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_appuser_no_show_locked_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequestHeadshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=api.storage.PrivateMediaStorage(),
                        upload_to=api.models._headshot_multi_upload_path,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headshots",
                        to="api.accessrequest",
                    ),
                ),
            ],
            options={
                "db_table": "access_request_headshot",
            },
        ),
        migrations.AddIndex(
            model_name="accessrequestheadshot",
            index=models.Index(
                fields=["request", "created_at"],
                name="access_request_headshot_request_created_idx",
            ),
        ),
    ]
