# Generated by Django 5.2 on 2026-01-08 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_access_request_headshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_pax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_pax', models.PositiveIntegerField(default=1)),
                ('max_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catering_package',
            },
        ),
        migrations.CreateModel(
            name='CateringPackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity_per_pax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'menu_item',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='catering_package_items',
                        to='api.menuitem',
                    ),
                ),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='api.cateringpackage',
                    ),
                ),
            ],
            options={
                'db_table': 'catering_package_item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='events',
                to='api.cateringpackage',
            ),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='package_price_per_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='package_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='cateringpackage',
            index=models.Index(fields=['name'], name='catering_pa_name_8bf043_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringpackage',
            index=models.Index(fields=['active'], name='catering_pa_active_f82b95_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringpackageitem',
            index=models.Index(fields=['package'], name='catering_pa_package_a199b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringpackageitem',
            index=models.Index(fields=['menu_item'], name='catering_pa_menu_it_0831ba_idx'),
        ),
    ]
