# Generated by Django 5.2 on 2026-01-09 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_team_composition_targets_exceptions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessrequestheadshot',
            new_name='access_requ_request_de60e9_idx',
            old_name='access_request_headshot_request_created_idx',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pax_per_preparation',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of pax available per batch'),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
