# Generated by Django 5.2 on 2026-01-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_employee_hire_date'),
        ('api', '0062_rename_access_request_headshot_request_created_idx_access_requ_request_de60e9_idx_and_more'),
    ]

    operations = [
    ]
