# Generated by Django 5.2 on 2026-01-14 07:25

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_merge_20260114_0706"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarException",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(choices=[("holiday", "Holiday"), ("no_work", "No work day")], default="holiday", max_length=16)),
                ("scope", models.CharField(choices=[("all", "All staff"), ("roles", "Roles only")], default="all", max_length=16)),
                ("roles", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_workday_override", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calendar_exceptions", to="api.appuser")),
            ],
            options={
                "db_table": "calendar_exception",
                "ordering": ["date", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="calendarexception",
            index=models.Index(fields=["date"], name="calendar_exc_date_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarexception",
            index=models.Index(fields=["kind", "date"], name="calendar_exc_kind_date_idx"),
        ),
    ]
