# Generated by Django 5.2 on 2026-01-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_calendar_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
    ]
